wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 1024
loss_function:
  desc: null
  value: sparse_categorical_crossentropy
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-10
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704710359.300279
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
