wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
momentum:
  desc: null
  value: 0.9
epochs:
  desc: null
  value: 5
loss_function:
  desc: null
  value: tf.keras.losses.BinaryCrossentropy()
architecture:
  desc: null
  value: MLP
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704726144.14916
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 7
      - 16
      - 23
      - 38
      - 39
      4: 3.10.12
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/binary_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_binary_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
