wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
momentum:
  desc: null
  value: 0.9
epochs:
  desc: null
  value: 5
loss_function:
  desc: null
  value: <keras.src.losses.BinaryCrossentropy object at 0x7f61501088b0>
architecture:
  desc: null
  value: MLP
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1704712640.678181
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
